version: "3.8"
services:
  postgresql:
    image: postgres:16
    ports:
      - "5430:5432"
    volumes:
      - ./db/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scrapper
    container_name: postgresDB
    networks:
      - backend

  liquibase-migrations:
      image: liquibase/liquibase:4.25
      depends_on:
        - postgresql
      command:
        - --changelog-file=master.xml
        - --driver=org.postgresql.Driver
        - --url=jdbc:postgresql://postgresql:5432/scrapper
        - --username=postgres
        - --password=postgres
        - update
      container_name: liquibase
      volumes:
        - ./db/migrations:/liquibase/changelog
      networks:
        - backend

volumes:
  postgresql: { }

networks:
  backend: { }
