app:
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper

server:
  port: 8080

endpoints:
  bot: http://localhost:8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
