app:
  telegram-token: ${BOT_TOKEN}
  botName: ${BOT_NAME}

spring:
  application:
    name: ${BOT_NAME}
  jackson:
    time-zone: UTC

server:
  port: 8090

endpoints:
  scrapper: http://localhost:8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
