app:
  telegram-token: ${BOT_TOKEN}
  botName: ${BOT_NAME}

spring:
  application:
    name: ${BOT_NAME}
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
